services:
  chrome:
    image: selenium/standalone-chrome:124.0-20250414
    shm_size: "12gb"
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "4444:4444"
      - "7900:7900"   
    restart: always
    networks: 
      - lakehouse_internal_net 


  


