# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry=true

[sources.resources.mflix_mongodb]
collections=["movies", "comments", "users", "theaters"]

[sources.resources]
database_name="sample_mflix"
batch_size=1000

