[sources.resources]
mongodb_connect="mongodb+srv://AdminMola:MolaMola123@molanpl.gplydvn.mongodb.net/"

[destination.postgres]
credentials="postgresql://nguyenphuclinh:Lt251208@localhost:5432/mflix_db?connect_timeout=15"
