networks:
  monitoring-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}

services:
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      # - ./prometheus/rules:/etc/prometheus/rules # Bỏ comment nếu sau này có file rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9090'
      - '--web.enable-lifecycle' # Cho phép reload cấu hình qua API
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1 
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    # Không cần expose port 9100 ra ngoài host, Prometheus truy cập qua internal network
    pid: host # Cần thiết để lấy một số metrics process từ host
    networks:
      - monitoring-net
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.28.1 
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=:9093'
    ports:
      - "9093:9093"
    networks:
      - monitoring-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.4 
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning # Provisioning datasources, dashboards
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini # Mount file ini nếu cần tùy chỉnh sâu
    environment:
      - GF_SECURITY_ADMIN_USER=NguyenPhucLinh
      - GF_SECURITY_ADMIN_PASSWORD=NguyenPhucLinh
      # - GF_INSTALL_PLUGINS= # Thêm plugin nếu cần, ví dụ: grafana-clock-panel
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    restart: unless-stopped
