volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}
  
services:
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./Monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      # - ./prometheus/rules:/etc/prometheus/rules # Bỏ comment nếu sau này có file rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9090'
      - '--web.enable-lifecycle' # Cho phép reload cấu hình qua API
    ports:
      - "9090:9090"
    networks:
      - lakehouse_internal_net
    restart: unless-stopped
    depends_on:
      - pushgateway
      - cadvisor # Đảm bảo cAdvisor khởi động để Prometheus có thể scrape

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    volumes:
      - ./Monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=:9093'
    ports:
      - "9093:9093"
    networks:
      - lakehouse_internal_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.4
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Monitoring/grafana/provisioning:/etc/grafana/provisioning # Provisioning datasources, dashboards
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini # Mount file ini nếu cần tùy chỉnh sâu
    environment:
      - GF_SECURITY_ADMIN_USER=NguyenPhucLinh
      - GF_SECURITY_ADMIN_PASSWORD=NguyenPhucLinh
      # - GF_INSTALL_PLUGINS= # Thêm plugin nếu cần, ví dụ: grafana-clock-panel
    ports:
      - "3000:3000"
    networks:
      - lakehouse_internal_net
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.11.1
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - lakehouse_internal_net
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0 # Sử dụng phiên bản cụ thể
    container_name: cadvisor
    privileged: true # cAdvisor thường cần quyền này để truy cập đầy đủ thông tin host và Docker
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # Cho phép cAdvisor truy cập Docker socket
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8085:8080" # Cổng web UI và metrics của cAdvisor
    networks:
      - lakehouse_internal_net
    restart: unless-stopped
