services:
  spark-master:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-master
    hostname: spark-master
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure

  spark-worker-1:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-1
    hostname: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure

  spark-worker-2:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-2
    hostname: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure


