services:
  spark-master:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-master
    hostname: spark-master
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master RPC
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure

  spark-worker-1:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-1
    hostname: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Spark Worker 1 Web UI
      - "4041:4040" # THÊM DÒNG NÀY: Ánh xạ Application UI của driver chạy trên worker 1
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_WEBUI_PORT: 8081 # Cổng Web UI của Worker (khác với Application UI)
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure

  spark-worker-2:
    image: apache/spark:3.5.5-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-2
    hostname: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class"]
    command: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # Spark Worker 2 Web UI (Container port là 8081, host port là 8082)
      - "4042:4040" # THÊM DÒNG NÀY: Ánh xạ Application UI của driver chạy trên worker 2 ra cổng 4041 của host
    volumes:
      - ./Apache_Spark/apps:/opt/spark/apps
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_WEBUI_PORT: 8081 # Cổng Web UI của Worker
      SPARK_RPC_AUTHENTICATION_ENABLED: false
      SPARK_RPC_ENCRYPTION_ENABLED: false
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: false
      SPARK_SSL_ENABLED: false
    networks:
      - lakehouse_internal_net
    restart: on-failure


